version: '3.8'

volumes:
  app-dist:


services:
  comfyui:
    build:
      context: ./ComfyUI-Launcher/
      dockerfile: Dockerfile
    container_name: comfyui
    volumes:
      - ../workspace/comfyui_launcher/models:/app/server/models
      - ../workspace/comfyui_launcher/projects:/app/server/projects
      - ../workspace/comfyui_launcher/input:/app/server/input
      - ../workspace/comfyui_launcher/output:/app/server/output
    restart: always
    ports:
      - "4000-4100:4000-4100"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - PROXY_MODE=true
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=EEST
    volumes:
      - /home/f0kes/workspace/syncthing/config:/config
      - ../workspace/comfyui_launcher/models:/models
      - ../workspace/comfyui_launcher/input:/input
      - ../workspace/comfyui_launcher/output:/output
    ports:
      - 8384:8384 # Syncthing GUI port
      - 22000:22000 # Syncthing protocol port
      - 21027:21027/udp # Syncthing discovery port
  anim_frontend:
    build:
      context: ./fil_anim_starter/frontend/sveltekit
      dockerfile: Dockerfile
    container_name: anim_frontend

    restart: always
    ports:
      - "3000:3000"
    volumes:
      - app-dist:/app/dist
    environment:
      - NODE_ENV=development
    depends_on:
      - comfyui
      - anim_backend

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - app-dist:/etc/nginx/html
    restart: always
    ports:
      - "4242:80"
    depends_on:
      - comfyui
      - syncthing
      - anim_backend
      - anim_frontend
  anim_backend:
    build:
      context: ./fil_anim_starter/backend
      dockerfile: Dockerfile
    container_name: anim_backend
    volumes:
      - ../workspace/anim_backend:/data
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - comfyui
  flux_comfy:
    image: yanwk/comfyui-boot:cu121
    container_name: flux_comfy
    volumes: 
      - ../workspace/flux_comfy:/home/runner
    restart: always
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
