version: '3.8'

services:
  pytorch:
    image: pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel # Replace with the actual image name from Docker Hub
    container_name: pytorch
    volumes:
      - ../workspace:/workspace
    restart: always
    ports:
      - "8188:8188"
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/htpasswd:/etc/nginx/.htpasswd
    restart: always
    ports:
      - "4242:80"
    depends_on:
      - pytorch
